name = "dns-bot"
main = "src/index.ts"
compatibility_date = "2024-02-20"

# KV Namespace configuration
kv_namespaces = [
  { binding = "DNS_KV", id = "9c9e35db9cdf483784ccdadd5bdd24a7" }
]

# Cron trigger configuration (runs every minute)
[triggers]
crons = ["* * * * *"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



